  sgep:
    viaCep:
      url: ${SGEP_VIACEP_URL}

  spring:
    application:
      name: FinancialSystem
    cloud:
      function:
        definition:
          createContractEvent;
          createCustomerEvent;
          createPaymentEvent;
      stream:
        bindings:
          createContractEvent-in-0:
            destination: sgep-contract-events
            group: sgep-loan-events-group
            content-type: application/json
          createCustomerEvent-in-0:
            destination: sgep-customer-events
            group: sgep-loan-events-group
            content-type: application/json
          createPaymentEvent-in-0:
            destination: sgep-payment-events
            group: sgep-loan-events-group
            content-type: application/json
        binders:
          loan:
            type: kafka
            environment:
              spring.cloud.stream.kafka:
                binder:
                  brokers: ${SGEP_BROKERS_LOCALHOST_PORT}
                  producer-properties:
                    key.serializer: org.apache.kafka.common.serialization.StringSerializer
                  autoCreateTopics: true
      openfeign:
        client:
          config:
            viaCepFeign:
              connectTimeout: ${SGEP_OPENFEIGN_CONNECT_TIMEOUT}
              readTimeout: ${SGEP_OPENFEIGN_READ_TIMEOUT}

  resilience4j:
    retry:
      configs:
        default:
          maxAttempts: ${SGEP_RETRY_MAX_ATTEMPTS}
          waitDuration: ${SGEP_RETRY_WAIT_DURATION}
      instances:
        viaCepRetry:
          maxAttempts: ${SGEP_VIACEP_MAX_ATTEMPTS}
          waitDuration: ${SGEP_VIACEP_WAIT_DURATION}
    data:
      mongodb:
        uri: ${SGEP_MONGODB_URL}

  springdoc:
    api-docs:
      path: /api-docs
      resolve-schema-properties: true
    override-with-generic-response: false
    default-produces-media-type: application/json
    default-consumes-media-type: application/json
    paths-to-exclude: /**/api-docs,/swagger-resources/**
    writer-with-order-by-keys: true
    swagger-ui:
      path: /
      tags-sorter: alpha
      operations-sorter: alpha
      doc-expansion: none
    packages-to-scan:
      - com.example.FinancialSystem.entryPoint.controller