  spring:
    application:
      name: FinancialSystem
    cloud:
      function:
        definition: createLoanEvent
      stream:
        bindings:
          createContractEvent-in-0:
            destination: sgep-contract-events
            group: sgep-contract-events-group
            content-type: application/json
          createCustomerEvent-in-0:
            destination: sgep-customer-events
            group: sgep-loan-events-group
            content-type: application/json
          createPaymentEvent-in-0:
            destination: sgep-payment-events
            group: sgep-loan-events-group
            content-type: application/json
        binders:
          loan:
            type: kafka
            environment:
              spring.cloud.stream.kafka:
                binder:
                  brokers: localhost:9092
                  producer-properties:
                    key.serializer: org.apache.kafka.common.serialization.StringSerializer
                  autoCreateTopics: true

    data:
      mongodb:
        uri: mongodb://localhost:37017/financial-system

  springdoc:
    api-docs:
      path: /api-docs
      resolve-schema-properties: true
    override-with-generic-response: false
    default-produces-media-type: application/json
    default-consumes-media-type: application/json
    paths-to-exclude: /**/api-docs,/swagger-resources/**
    writer-with-order-by-keys: true
    swagger-ui:
      path: /
      tags-sorter: alpha
      operations-sorter: alpha
      doc-expansion: none
    packages-to-scan:
      - com.example.FinancialSystem.entryPoint.controller